### ISSUE TITLE
5.0.7 - Could not find 'navigator.clipboard.writeText'

### ISSUE THREAD

**Issue by emoeckel** [ironmansoftware/powershell-universal#3774] opened 2024-09-16 16:11 UTC
### Version

5.0.6

### Severity

Low

### Environment

msi

### Steps to Reproduce

Version 5.0.7
API Endpoint > Edit Code > Test Tab > Copy Button for URL Section

### Expected behavior

```console
Copies to Clipboard
```

### Actual behavior

```console
Big Ole Red Message:

An error occured. Could not find 'navigator.clipboard.writeText' ('clipboard' was undefined). findFunction/<@http://igqprmgtpsu01:443/_framework/blazor.server.js:1:537 findFunction@http://igqprmgtpsu01:443/_framework/blazor.server.js:1:505 _@http://igqprmgtpsu01:443/_framework/blazor.server.js:1:5248 beginInvokeJSFromDotNet/s<@http://igqprmgtpsu01:443/_framework/blazor.server.js:1:3041 beginInvokeJSFromDotNet@http://igqprmgtpsu01:443/_framework/blazor.server.js:1:3004 _invokeClientMethod@http://igqprmgtpsu01:443/_framework/blazor.server.js:1:60890 _processIncomingData@http://igqprmgtpsu01:443/_framework/blazor.server.js:1:58279 Xt/this.connection.onreceive@http://igqprmgtpsu01:443/_framework/blazor.server.js:1:51920 connect/</s.onmessage@http://igqprmgtpsu01:443/_framework/blazor.server.js:1:80026
at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args) at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args) at PowerShellUniversal.EndpointTester.CopyUrl() in C:\actions-runner\_work\universal\universal\src\Universal.Server\Shared\APIs\EndpointTester.razor:line 237 at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task) at AntDesign.Button.HandleOnClick(MouseEventArgs args) at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task) at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

### Additional Environment data

5.0.7

**Comment by adamdriscoll** [comment] 2024-09-16 16:50
@emoeckel Can you let me know what browser you are using? I can't reproduce in Edge or Firefox.

**Comment by emoeckel** [comment] 2024-09-16 17:44
> @emoeckel Can you let me know what browser you are using? I can't reproduce in Edge or Firefox.

@adamdriscoll Tried on both, same behavior

Firefox 130.0
Chrome 128.0.6613.138

**Comment by adamdriscoll** [comment] 2024-09-16 17:56
It looks like on 8/26 we implemented a fix for this: https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined

Can you try clearing your browser cache? I think some of the JS might be cached (site.js). We need to fix that...

**Comment by emoeckel** [comment] 2024-09-16 18:30
> It looks like on 8/26 we implemented a fix for this: https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined
> 
> Can you try clearing your browser cache? I think some of the JS might be cached (site.js). We need to fix that...

@adamdriscoll 

I did clear my cache, actually everything for chrome. Same behavior. However, I changed the PSU site to https instead of http over 443, and that is now working for both browsers. It may be a org security setting, not sure.

Thanks!

**Comment by adamdriscoll** [comment] 2024-09-16 18:37
Sounds good. I've introduced versioning to the JS file a well in case that does cause other issues.

**Closed as completed by adamdriscoll** 2024-09-16 18:37 UTC
Labels: bug, PowerShell Universal, P4 - low, Area-AdminConsole, Size - S
