### ISSUE TITLE
List of links that do not work in nested IIS and General QA

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3345] opened 2024-05-21 20:27 UTC
### Version

5.0.0-beta5 (9200108868)

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

when i visit the health checks from the home admin site i cannot get to the page

the base admin url looks like this: https://dev.psu.domain.com/Beta/admin

List of URLs that suffer from this issue:
- https://dev.psu.domain.com/Beta/admin/apis/endpoints?page=1&size=5
- https://dev.psu.domain.com/Beta/admin/automation/terminals
- https://dev.psu.domain.com/Beta/admin/platform/translations
- https://dev.psu.domain.com/Beta/admin/settings/branding
- https://dev.psu.domain.com/Beta/apps/docs

### Expected behavior

```console
Example:
https://dev.psu.domain.com/Beta/admin/platform/health-checks
200
```

### Actual behavior

```console
Example:
https://dev.psu.domain.com/admin/platform/health-checks
404
```

**Comment by Omzig** [comment] 2024-05-23 15:59
@adamdriscoll, if we could get this into a nightly build, i can test some more before 5.0 is released.

**Comment by adamdriscoll** [comment] 2024-05-29 19:40
These should be fixed in nightly but I still need to test.

**Comment by Omzig** [comment] 2024-05-30 14:58
@adamdriscoll, /portal/services does not work, i forgot to list it

**Comment by Omzig** [comment] 2024-06-06 16:14
@adamdriscoll, new list of URLS that do not work:

## /admin
- click git sync enable, takes you to https://dev.psu.domain.com/admin/settings/git
- click edit, then click save on git takes you to: https://dev.psu.domain.com/admin/settings/git/commit
## /admin/apis/endpoints
- API Documentation button that takes you to swagger gives a 404:
- https://dev.psu.domain.com/swagger, should go to https://dev.psu.domain.com/beta/swagger
- Import From library button does not work: https://dev.psu.domain.com/admin/platform/library?type=API
## /Beta/admin/automation/scripts
- Import From Library does not work: https://dev.psu.domain.com/admin/platform/library?type=Script
## /Beta/admin/automation/terminals
- Terminal Instances does not work
- Import from Library does not work
## /Beta/admin/automation/triggers
- Import from Library does not work
## /Beta/admin/automation/triggers
- ![image](https://github.com/ironmansoftware/issues/assets/1987296/78e1aa07-fdd7-4829-9456-45c114a29ec8)
- Enter License Key does not work
- and why is it asking in the first place?
## /Beta/admin/apps/blazor
- Import from Library does not work
## /Beta/admin/apps/powershell
- Import from Library does not work
## /Beta/admin/platform/computers
- ![image](https://github.com/ironmansoftware/issues/assets/1987296/b24f39e5-50bd-4d18-a553-54eeb170d552)
## /Beta/admin/platform/library
- links to behind the github icons do not go to places that exist
## /Beta/admin/platform/logging/targets
- Import from Library does not work
## /Beta/admin/platform/logging/files
- Download button downloads a zip file that is empty
## /Beta/admin/settings/environments
- Restart button doesn't make an api call, just spins
- Discover Environments does not make an api call

**Comment by adamdriscoll** [comment] 2024-06-06 21:09
Fixed all the issues. Some comments below. 

# /Beta/admin/automation/triggers

Can't reproduce this license nag but did fix the button on it. 

# /Beta/admin/platform/computers

This will go away once out of beta

# /Beta/admin/platform/library

Looks like the local accounts one is broken but other work. I will have to fix that on the scripts repo. 

# /Beta/admin/settings/environments

Blazor only makes websocket calls so you won't see any API calls. Fixed the restart button.

**Comment by Omzig** [comment] 2024-06-07 20:48
# build: 9409543299
# /Beta/admin/settings/licenses
unable to delete a license

**Comment by Omzig** [comment] 2024-06-07 20:58
> Fixed all the issues. Some comments below.
> 
> # /Beta/admin/automation/triggers
> Can't reproduce this license nag but did fix the button on it.
> 
> # /Beta/admin/platform/computers
> This will go away once out of beta
> 
> # /Beta/admin/platform/library
> Looks like the local accounts one is broken but other work. I will have to fix that on the scripts repo.
> 
> # /Beta/admin/settings/environments
> Blazor only makes websocket calls so you won't see any API calls. Fixed the restart button.

So, i checked, you fixed it :)

**Comment by adamdriscoll** [comment] 2024-06-08 19:48
> # build: 9409543299
> # /Beta/admin/settings/licenses
> unable to delete a license

Fixed.

**Comment by Omzig** [comment] 2024-06-10 13:48
> > # build: 9409543299
> > # /Beta/admin/settings/licenses
> > unable to delete a license
> 
> Fixed.

with git settings set to One-Way, i am unable to delete the license: 
![image](https://github.com/ironmansoftware/issues/assets/1987296/90097d58-8f4c-4aef-b3a7-3a3fa4bdd8f2)

**Comment by Omzig** [comment] 2024-06-11 13:46
@adamdriscoll, this link does not work, clicking the licensed label forgets that you are in a nested site:
![image](https://github.com/ironmansoftware/issues/assets/1987296/f6bf403b-0bce-466d-ba0f-6cb0eb889180)

**Comment by adamdriscoll** [comment] 2024-06-18 20:54
I think all of these issues are fixed. Feel free to reopen if this isnt the case.

**Closed as completed by adamdriscoll** 2024-06-18 20:54 UTC
Labels: bug, PowerShell Universal, requires triage, beta, P4 - low, Area-AdminConsole, Size - XS
