### ISSUE TITLE
Variables page is blank

### ISSUE THREAD

**Issue by bt-ndollimount** [ironmansoftware/powershell-universal#4007] opened 2024-11-01 13:10 UTC
### Description of Issue

Expand Platform and click Variables. The page is loading blank.

### Version

5.0.14

### Severity

High

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

PostgreSQL

### Licensed

Yes

### Features

Git sync

### Additional Environment data

Instances running on both Windows and Linux are displaying the same issue.

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/d62ec06f-1466-4b03-9890-149d13991ed4)

**Comment by adamdriscoll** [comment] 2024-11-01 13:38
Duplicate of #4002 - I'll release early next week since this is high impact.

**Closed as completed by adamdriscoll** 2024-11-01 13:38 UTC
Labels: bug, PowerShell Universal, requires triage, v5
