### ISSUE TITLE
Scripts executed in custom PWSH environment fails

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#3730] opened 2024-09-09 23:04 UTC
### Version

5.0.6

### Severity

Medium

### Environment

msi

### Steps to Reproduce

Upgraded from 4.4.0 to 5.0.6

When executing new and old scripts with a custom environment, that was created in version 4.X, the script then fails to execute - no matter how simple the content is.
This script contains `"Works"` and thats all

![image](https://github.com/user-attachments/assets/6956c636-ad40-4159-851f-7036f3d2c19b)

![image](https://github.com/user-attachments/assets/c9011b8b-6b71-4a9f-b35f-db35fbd25a73)

### Expected behavior

```console
That it would execute the script
```

### Actual behavior

```console
It does not actually execute the script
```

**Comment by adamdriscoll** [comment] 2024-09-10 13:59
I can't reproduce this error. I'm not sure if it's related to 3732 but I was able to fix that. We had an assembly conflict that should be resolved. 

Do you happen to have another Universal module version installed? 

```
Get-Module Universal -List
```

**Comment by ksl28** [comment] 2024-09-10 15:40
Nope - i already checked that, following the upgrade guide. (Great job on that btw).
![image](https://github.com/user-attachments/assets/5598d8e6-48b9-4450-834e-25763aed5cbc)

**Comment by ksl28** [comment] 2024-09-10 16:55
I ended up removing version 5.0.6 and installed it "fresh" again, but with the appsettings.json and SQL database still in place.
Now it works as expected.

**Comment by adamdriscoll** [comment] 2024-09-10 23:18
Ok. I'm going to close this for now but if it resurfaces, let's reopen this.,

**Closed as completed by adamdriscoll** 2024-09-10 23:18 UTC
Labels: bug, PowerShell Universal, requires triage
