### ISSUE TITLE
5.0.15 | Favicon doesn't work if App URL is "/"

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#4055] opened 2024-11-13 15:28 UTC
### Description of Issue

The title should be clear I think... :-D
- Create an App and specify the URL to be "/" ==> The favicon won't display. Instead it will use the default PSU Icon
- Now change the URL to "/whatever" ==> The favicon will display correctly.

### Version

5.0.15

### Severity

Visual

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQL

### Licensed

Yes

**Comment by adamdriscoll** [comment] 2024-11-18 18:31
I can't reproduce this. Here's my configuration.

Published Folder

```
New-PSUPublishedFolder -RequestPath "/icons" -Path "Folder2" -Name "Folder"
```

App

```
New-PSUApp -Name "App1" -FilePath "dashboards\App1\App1.ps1" -BaseUrl "/" -Authenticated -AutoDeploy -FavIcon "/icons/favicon.ico"
```

That said, it seems like this could be a caching problem when more than one app is defined.

**Comment by donlent** [comment] 2024-11-18 19:01
Hi Adam 
OK thanks a lot! Will try to check what you mentioned regarding cache and multiple apps and will let you know latest on Wednesday.

**Comment by diegovdw** [comment] 2024-11-19 09:41
Hi
I've actually also opened this bug in #3873 which was closed as fixed but it wasn't.
Some more info that i've added after it was closed:

The current logo of the app with url "/" is udfavicon.ico and doesn't seem to be overwritten by the setting in the app for favicon

The app favicon is configured with: /assets/logos/cg_logo_short.png (valid png in a published folder)
The icon i receive in the html of the root app: seems to still be coming from the main installation folder. -> https://psu-url/udfavicon.ico

I currently cheated the system by backing up udfavicon.ico and replacing it with my own in C:\Program Files (x86)\Universal\wwwroot and this seems to fix the icon issue with the app with url "/", however this is not ideal

@donlent i hope you are referring to the same issue and please remove if it isn't, but i think it is.

**Comment by adamdriscoll** [comment] 2024-11-19 16:04
I've changed how this works. It was doing a redirect that was causing the caching issue and who knows what with multiple apps. It just does a HTML rewrite to set the proper URL now.

**Closed as completed by adamdriscoll** 2024-11-19 16:04 UTC
Labels: bug, PowerShell Universal, P4 - low, Area-Apps, Size - S, v5
