### ISSUE TITLE
Event Log Warning opening non-existent drive.

### ISSUE THREAD

**Issue by Artanor** [ironmansoftware/powershell-universal#1548] opened 2022-09-12 10:27 UTC
### Steps to Reproduce

I noticed in the Event Log the following warnings.

Provider Health: Could not find the drive 'T:\'. The drive might not be ready or might not be mapped.. 

Details: 
	ProviderName=Microsoft.PowerShell.Core\FileSystem
	ExceptionClass=DriveNotFoundException
	ErrorCategory=
	ErrorId=
	ErrorMessage=Could not find the drive 'T:\'. The drive might not be ready or might not be mapped.

	Severity=Warning

	SequenceNumber=78

	HostName=Universal Automation Host
	HostVersion=1.0
	HostId=9ccbc302-d2d1-4107-8d74-671bb764ade6
	HostApplication=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -Command & { [System.Reflection.Assembly]::LoadFrom('C:\Program Files (x86)\Universal\Host\host.dll') | Out-Null; [UniversalHost.AgentService]::StartJob(53516, 3564, $False, 50676) }
	EngineVersion=5.1.17763.2931
	RunspaceId=14ad4cea-73be-4e0f-abc3-7dfe8a91f7c3
	PipelineId=2
	CommandName=
	CommandType=
	ScriptName=
	CommandPath=
	CommandLine=

### Expected behavior

```console
I Don't expect to see errors relating to non-existent drives.
```

### Actual behavior

```console
The above warning is logged in the event log.
```

### Environment data

PSU Version 3.2.8

**Comment by DataTraveler1** [comment] 2022-09-12 17:14
@Artanor - Please feel free to use the 'Contact Us' feature on the ironmansoftware.com to log a ticket with @adamdriscoll 

### Information Requested

I don't believe that PSU will create such log entries out of the box. We need to isolate this to understand where it's coming (process of elimination)

1) Which log in the event viewer is this coming from? Application, System, PowerShell?
2) What is the ID number of the event?
3) Can we have screenshots and logs (best uploaded through a support ticket by using 'Contact Us' on ironmansoftware.com)

### Actions Requested

a) Share your code which produces this behavior
or
b) Install PSU in a fresh test environment and confirm that you're not seeing this error there

**Comment by adamdriscoll** [comment] 2022-09-12 19:32
Just chiming in that @DataTraveler1 @Artanor this may be related to the translation provider: https://docs.powershelluniversal.com/platform/translations#using-strings

**Comment by Artanor** [comment] 2022-09-13 08:28
I don't use the translation provider myself and a quick search of my repository doesn't show any instances of using t:

I have not seen this again today despite a restart of UD. I'll check if it was related to the installation process next time I upgrade.

That said here's the XML Data from event viewer.

[event300.txt](https://github.com/ironmansoftware/issues/files/9555045/event300.txt)

**Comment by adamdriscoll** [comment] 2022-09-23 19:58
I'll close this issue for now since it isn't reproducible be feel free to reopen it if you still encounter it.

**Closed as not planned by adamdriscoll** 2022-09-23 19:58 UTC
Labels: bug, PowerShell Universal
