### ISSUE TITLE
5.0.X : Page size selector is not saved

### ISSUE THREAD

**Issue by Er-Yas** [ironmansoftware/powershell-universal#4058] opened 2024-11-14 14:27 UTC
### Summary of the new feature / enhancement

Page size selector was available on version 4.X on many admin pages : endpoints / jobs / schedules / roles / .... 
Now the problem is that the choice is not saved.

If I put 100 page size, and go elsewhere and come back, it's back to 5

**Comment by adamdriscoll** [comment] 2024-11-14 15:01
Duplicate of #4023

**Closed as completed by adamdriscoll** 2024-11-14 15:01 UTC
Labels: enhancement, PowerShell Universal
