### ISSUE TITLE
Search function in Table column

### ISSUE THREAD

**Issue by RubenT91** [ironmansoftware/powershell-universal#3246] opened 2024-04-06 06:29 UTC
### Version

4.2.15

### Severity

Low

### Environment

msi

### Steps to Reproduce

"undefined" parameter from search in a table column, search function seemed to be broken. not returning the right values.

### Expected behavior

```console
Provide a good result from the search in the filter option.
```

### Actual behavior

```console
The issue seems to be when there is a property under a property, this is causing the search not to display the right results.
```

### Visuals

![Screenshot 2024-04-06 011553](https://github.com/ironmansoftware/issues/assets/68939160/aebb5a0d-002e-48b6-9fe1-5b2d455c672d)

This is the undefined example:

![Undefined example](https://github.com/ironmansoftware/issues/assets/68939160/2f6216f2-9f4c-43b1-9245-fd20a370ee5f)

**Comment by adamdriscoll** [comment] 2024-04-28 21:21
```
$Data = @(
    @{Dessert = 'Frozen yoghurt'; Calories = 159; Fat = 6.0; Carbs = 24; Protein = [PSCustomObject]@{
        Object = "nice"
    }}
    @{Dessert = 'Ice cream sandwich'; Calories = 159; Fat = 6.0; Carbs = 24; Protein =@{
        Object = "nice"
    }}
    @{Dessert = 'Eclair'; Calories = 159; Fat = 6.0; Carbs = 24; Protein =@{
        Object = "nice"
    }}
    @{Dessert = 'Cupcake'; Calories = 159; Fat = 6.0; Carbs = 24; Protein = @{
        Object = "nice"
    }}
    @{Dessert = 'Gingerbread'; Calories = 159; Fat = 6.0; Carbs = 24; Protein =@{
        Object = "nice"
    }}
)

New-UDTable -Data $Data -ShowExport -Columns @(
New-UDTableColumn -Property Protein -OnRender {
    New-UDTypography $EventData.Protein.Object
} -FilterType text -ShowFilter


)
```

I can't reproduce this. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/725f3d45-7817-4fe7-86d6-39e8683a5a68)

**Comment by ksl28** [comment] 2024-05-02 04:15
@adamdriscoll - this is related to ticket #7998# 

Its still an issue on 4.2.20 - you can use this example to test with:

```
New-UDApp -Title 'PowerShell Universal' -Content {
    New-UDGrid -Container -Spacing 3 -content {
        New-UDGrid -ExtraSmallSize 6 -content {
            New-UDCard -Content {
                $Tickets = @()
                $ticket1 = [PSCustomObject]@{
                    data = @{
                        Name     = "Ticket 1"
                        Status   = "Open" 
                        Agent    = @{
                            Name = "Ron Swanson"
                        }
                        id = "1"
                    }
                }

                $ticket2 = [PSCustomObject]@{
                    data = @{
                        Name     = "Ticket 2"
                        Status   = "Open" 
                        Agent    = @{
                            Name = ""
                        }
                        id = "2"
                    }
                }

                $ticket3 = [PSCustomObject]@{
                    data = @{
                        Name     = "Ticket 3"
                        Status   = "Open" 
                        Agent    = @{
                            Name = "Donald Duck"
                        }
                        id = "3"
                    }
                }

                $Tickets += $ticket1
                $Tickets += $ticket2
                $Tickets += $ticket3

                $Columns = @(
                    New-UDTableColumn -Property Name -Title Name -ShowSort -IncludeInExport -ShowFilter
                    New-UDTableColumn -Property Status -ShowSort -IncludeInExport
                    New-UDTableColumn -Property Agent.Name -Title "Agent" -ShowSort -SortType basic -ShowFilter -FilterType text -IncludeInExport -Render {
                        if ($eventdata.Agent.Name) {
                            $eventdata.Agent.Name 
                        }
                    }
                    New-UDTableColumn -Property id -Title "Ticket ID" -ShowFilter -SortType alphanumeric -ShowSort -IncludeInExport
                )
                New-UDTable -Data $Tickets.data -Columns $Columns -ShowExport -PageSize 20 -PageSizeOptions @(10, 20, 30) -DisablePageSizeAll -Dense -ShowPagination -ShowSort -DefaultSortDirection descending 
            }
        }
    }

```

![image](https://github.com/ironmansoftware/issues/assets/53445047/1d639832-2fce-4f5c-9513-3510fc01bfe2)

**Comment by adamdriscoll** [comment] 2024-06-10 16:04
After looking at this more, the reason this isn't working is the nested object. 

```powershell
  Agent    = @{
      Name = "Donald Duck"
  }
```

While you are rendering to a flat object, it is still trying to filter by the object in the background and it won't work with nested properties like this. The only way to achieve this would be to change your data model to simplify the Agent property to just be a property of the main object. 

```powershell

                $ticket3 = [PSCustomObject]@{
                    data = @{
                        Name     = "Ticket 3"
                        Status   = "Open" 
                        AgentName    = "Donald Duck"
                        id = "3"
                    }
                }
```

Closing as this is expected behavior.

**Closed as not planned by adamdriscoll** 2024-06-10 16:04 UTC
Labels: bug, PowerShell Universal, requires triage, P4 - low
