### ISSUE TITLE
Missing IIS Websocket check

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2364] opened 2023-05-01 15:14 UTC
### Version

4.0.0-beta2  (4847121620)

### Severity

Low

### Steps to Reproduce

open health checks

### Expected behavior

```console
Websockets installed
```

### Actual behavior

```console
no record
```

### Additional Environment data

IIS: Nested

### Visuals

![image](https://user-images.githubusercontent.com/1987296/235474884-87ae26e1-86db-4fec-b863-c4b7b62cd43f.png)

**Comment by adamdriscoll** [comment] 2023-05-01 15:18
This is likely the same issue here: https://github.com/ironmansoftware/issues/issues/2313 

Please see my comment on that issue.

**Comment by adamdriscoll** [comment] 2023-05-01 20:15
Closing as this is the same issue as #2313 but because we changed how health checks are run (won't run on systems where it is not valid to run), it changes the behavior slightly. Can you please check that you have an $Env:APP_POOL_ID environment variable defined in this environment? I cannot reproduce this on my nested IIS site.

**Closed as not planned by adamdriscoll** 2023-05-01 20:15 UTC
Labels: bug, PowerShell Universal, requires triage, Core, beta, P4 - low
