### ISSUE TITLE
New-UDTable - Expanded Row is incorrect when data is changed

### ISSUE THREAD

**Issue by JoriPS1** [ironmansoftware/powershell-universal#2221] opened 2023-03-20 21:00 UTC
### Steps to Reproduce

Consider the following code sample..

```
New-UDDashboard -Title 'PowerShell Universal' -content {
    $Data = @"
[
    {
        "Name":  "User 1",
        "Email":  "User1@test.net",
        "Office":  "Office 1",
        "Title":  "Super Cool"
    },
    {
        "Name":  "User 2",
        "Email":  "User2@test.net",
        "Office":  "Office 2",
        "Title":  "2 Cool"
    }
]
"@ | ConvertFrom-Json
    
    New-UDTable -Data $Data -OnRowExpand {
        "This is $($Eventdata.name)"
    } -ShowSearch
}
```

When a row is expanded, and the data is filtered (e.g. through search) New-UDTable seems to expand the row that the previously expanded row was at (numerically).

### Expected behavior

```console
The proper row should be expanded, or at least collapsed.
```

### Actual behavior

```console
Whichever row number was expanded before is automatically expanded.
```

### Environment data

Confirmed on:
PSU: 3.7.10 & 3.8.3

### Visuals

**Here I have searched for "user2" and expanded the row.**

![image](https://user-images.githubusercontent.com/45468998/226463800-1566e11b-9835-4cd1-9459-20730125d0ec.png)

**Clearing the search yields this.**

![image](https://user-images.githubusercontent.com/45468998/226463889-acff8345-d9af-4afb-9ed2-ce82c281c8ab.png)

**Comment by donlent** [comment] 2023-03-21 09:43
This one is related to this... :-)
https://github.com/ironmansoftware/issues/issues/2205

**Comment by adamdriscoll** [comment] 2023-11-08 14:42
Duplicate of #2205

**Closed as completed by adamdriscoll** 2023-11-08 14:42 UTC
Labels: bug, PowerShell Universal
