### ISSUE TITLE
Add own icons to PSU

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#2309] opened 2023-04-12 17:14 UTC
### Summary of the new feature / enhancement

In #2191 @adamdriscoll did mention that you will remove the Pro icons.
That sad, I did notice that if you subscribe on fontawsome you can download the Pro icons.

So I function where you can add the icons to your psu server would be nice so that the customer can subscribe to the pro plan and use the icons in PSU.

### Proposed technical implementation details (optional)

Something like New-UDIcon -Custom "searchpath" then the ordinary parameters for New-UDIcon

**Comment by adamdriscoll** [comment] 2023-04-12 17:19
This is a duplicate of : #640

That said, I just moved it into the 4.0 milestone so we can figure out how to make it happen.

**Closed as completed by adamdriscoll** 2023-04-12 17:19 UTC
Labels: enhancement, PowerShell Universal
