### ISSUE TITLE
/admin/settings/files - After clicking on more than one file it doesn't show

### ISSUE THREAD

**Issue by mikedhanson** [ironmansoftware/powershell-universal#3609] opened 2024-08-21 12:43 UTC
### Version

5.0.0

### Severity

Low

### Environment

msi

### Steps to Reproduce

Navigate: /admin/settings/files
Click on a file (Should show the file) 
Click on another file and the script name updates but the script contents does not

![image](https://github.com/user-attachments/assets/c8b72a39-3a34-4b1b-88af-acae45aa4158)

### Expected behavior

```console
View the script
```

### Actual behavior

```console
does not update after clicking on more than one script.
```

**Comment by adamdriscoll** [comment] 2024-08-21 12:48
Duplicate of #3603

**Closed as not planned by adamdriscoll** 2024-08-21 12:48 UTC
Labels: bug, PowerShell Universal, requires triage
