### ISSUE TITLE
Support for Parameter Sets in PowerShell Universal API Endpoints

### ISSUE THREAD

**Issue by RubenT91** [ironmansoftware/powershell-universal#3907] opened 2024-10-14 14:45 UTC
### Summary of the new feature / enhancement

We are requesting the implementation of parameter sets in PowerShell Universal API endpoints. The ability to define and group parameters in API endpoints similar to how PowerShell cmdlets use parameter sets would provide a cleaner, more efficient way to manage API inputs. This feature would simplify mandatory parameter checks and avoid manual validation of parameter lengths or values, leading to clearer and more maintainable code. It would be especially helpful when defining multiple methods (GET, POST, PUT, etc.) for the same endpoint, like /pet, which is currently used as an example of this need.

This feature would benefit teams developing tools that need structured and consistent API handling, such as our ongoing rebuild of a helpdesk tool that relies heavily on API-based requests.

### Proposed technical implementation details (optional)

The implementation could follow the current PowerShell approach to parameter sets, allowing developers to group parameters and specify mandatory values directly in the API script.
Example syntax could resemble the following:
param (
    [Parameter(Mandatory = $true)]
    [string] $UserPrincipalName,

    [Parameter(Mandatory = $false)]
    [array] $Attributes,

    [Parameter(Mandatory = $true, ParameterSetName="Set1")]
    [string] $SessionID,

    [Parameter(Mandatory = $true, ParameterSetName="Set1")]
    [string] $RequestedBy,

    [Parameter(Mandatory = $true, ParameterSetName="Set2")]
    [string] $Property
)

This would enable cleaner validation and allow API authors to define how different parameters should be grouped and validated, removing the need for manual validation.

**Comment by adamdriscoll** [comment] 2024-10-14 15:41
This is a duplicate of: #3798 It is scheduled for 4.5 and likely  5.0.12 or 5.0.13.

**Closed as completed by adamdriscoll** 2024-10-14 15:41 UTC
Labels: enhancement, PowerShell Universal
