### ISSUE TITLE
POST API Endpoint with Authentication Broken

### ISSUE THREAD

**Issue by ph-cch** [ironmansoftware/powershell-universal#3858] opened 2024-10-03 15:06 UTC
### Version

5.0.9

### Severity

High

### Environment

IIS

### Steps to Reproduce

We have several POST API endpoints configured with authentication enabled.  Since the upgrade from 4.2.21 to 5.0.9 these are no longer working.  If the endpoint is configured with only the POST method then attempts to call the API will result in a 404 error, if the endpoint is re-configured to include the GET method then the request is processed as a GET request after the authentication process instead of a POST request.

Current code of testPOSTAuth endpoint:
```powershell
if ($Method -eq 'GET') {
    Write-Output "Auth successful for $Identity - Welcome!"
    Write-Output "You have submitted a GET request to this API"
}
elseif ($Method -eq 'POST') {
    Write-Output "Auth successful for $Identity - Welcome!"
    Write-Output "You have submitted a POST request to this API with the following body: $Body"
}
```

### Expected behavior

```console
Invoke-RestMethod -Uri $PSUniversalAPI -ContentType 'application/json' -Body '{"value":"TEST123"}' -Method 'POST' -UseDefaultCredentials

Result:

Auth successful for <user> - Welcome!
You have submitted a POST request to this API with the following body: '{"value":"TEST123"}'
```

### Actual behavior

```console
Invoke-RestMethod -Uri $PSUniversalAPI -ContentType 'application/json' -Body '{"value":"TEST123"}' -Method 'POST' -UseDefaultCredentials

Result:

Auth successful for <user> - Welcome!
You have submitted a GET request to this API
```

**Comment by adamdriscoll** [comment] 2024-10-03 18:52
I can reproduce a similar issue in Kestrel. Whatever it is will be resolved in 5.0.10. It looks like authorization isn't working for custom endpoints when using windows (default) authentication in 5.0.9. This may also affect the management API but still researching it.

**Comment by adamdriscoll** [comment] 2024-10-03 19:05
I found root cause. This will be included in our release on Monday.

**Closed as completed** 2024-10-03 19:05 UTC
Labels: bug, PowerShell Universal, support ticket, P2 - high, Area-API, Size - M

**Comment by Viajaz** [comment] 2024-10-04 01:22
@adamdriscoll This appears to be CVE-worthy. Please consider making internal unit tests for testing the authentication of endpoints.
