### ISSUE TITLE
Universal MSI Installer - Starting of Service

### ISSUE THREAD

**Issue by Viajaz** [ironmansoftware/powershell-universal#506] opened 2021-09-23 07:33 UTC
If appsettings.json is not to be migrated during an upgrade then please provide an option to disable the automatic starting of the PowerShell Universal service after install to prevent starting of the service, and any associated triggers, job, scripts etc. using an incorrect server configuration.

**Comment by adamdriscoll** [comment] 2022-03-18 13:44
Duplicate of #572

**Closed as completed by adamdriscoll** 2022-03-18 13:44 UTC
Labels: enhancement, PowerShell Universal
