### ISSUE TITLE
Separated authentication method for RestAPI calls

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#3528] opened 2024-08-02 07:53 UTC
### Summary of the new feature / enhancement

Hi,
It would be great if it was possible to have separated authentication method when your doing Rest API calls that are not made from the App / Dashboard.

For example;
When I'm calling a API from my personal computer using Powershell I want to have the possibility to limit this call to users that can authenticate with a certificate.

But if I visit my app trough the browser and a function within the app are calling the rest api I don't want to use certificate then I want to use as it is today the generated token that my user did get when they did login.

**Comment by adamdriscoll** [comment] 2024-08-02 13:43
Duplicate of: #1769

**Closed as completed by adamdriscoll** 2024-08-02 13:43 UTC
Labels: enhancement, PowerShell Universal
