### ISSUE TITLE
Cannot change Code in App Pages since Upgrade to 4.2.21

### ISSUE THREAD

**Issue by ganslm** [ironmansoftware/powershell-universal#3333] opened 2024-05-16 08:02 UTC
### Version

4.2.21

### Severity

High

### Environment

msi

### Steps to Reproduce

1. Create new App with the Template "Multiple Pages"
2. Edit the App
3. Try to change the Code of a Page

### Expected behavior

```console
Save the Code.
```

### Actual behavior

```console
Request failed with status code 400.
```

### Additional Environment data

Operating System: Windows Server 2022 Datacenter; Changing Code with the VS Code AddIn still works, but when I edit the App using the Website all changes done with VS Code are gone.

### Screenshots/Animations

![grafik](https://github.com/ironmansoftware/issues/assets/169981477/55184cdc-dc21-4755-b018-cce20e6f9cfb)

**Comment by adamdriscoll** [comment] 2024-05-20 13:37
We'll need to look in the system log to see what is causing the 400 error. I am not able to reproduce this.

**Comment by ganslm** [comment] 2024-05-21 06:06
Hi,

thanks for the reply.

I uploaded the system logs from today.

The last "Request failed with status code 400" was at 8am.

[systemLog20240521.txt](https://github.com/ironmansoftware/issues/files/15385225/systemLog20240521.txt)
[log20240521.txt](https://github.com/ironmansoftware/issues/files/15385226/log20240521.txt)
[systemLog20240521_001.txt](https://github.com/ironmansoftware/issues/files/15385227/systemLog20240521_001.txt)

**Comment by adamdriscoll** [comment] 2024-05-21 14:36
Thanks for the logs. It looks like one of the dashboard's name is null for some reason and causing this problem. I've put a check in place but I'm not sure what the root cause is. This will be fixed in the next version.

**Closed as completed by adamdriscoll** 2024-05-21 14:36 UTC
Labels: bug, PowerShell Universal, requires triage
