### ISSUE TITLE
Table Pagination not working on Server 2019 

### ISSUE THREAD

**Issue by gerane** [ironmansoftware/powershell-universal#83] opened 2021-03-24 13:42 UTC
**Describe the bug**
Table Pagination is not working on Server 2019. Same code works on Windows 10. If there are hundreds or thousands of rows it will display all of them without any sort of pagination.

**To Reproduce**

```powershell
$Columns = @(
    New-UDTableColumn -Property Name -Title Name -DefaultSortColumn -IncludeInSearch -IncludeInExport -Sort
    New-UDTableColumn -Property Name2 -Title Name2 -IncludeInSearch -IncludeInExport -Sort
    New-UDTableColumn -Property Name3 -Title Name3 -IncludeInSearch -IncludeInExport -Sort
    New-UDTableColumn -Property Name4 -Title Name4 -IncludeInSearch -IncludeInExport -Sort
)

New-UDTable -Data $Data -Columns $Columns -PageSize 10 -Dense -Search -Export
```

I have tried several different combos of params, but I haven't found a combination that works for pagination on Server 2019.

**Expected behavior**
Should have pagination like it does on Windows 10

**Screenshots**

**Version**

Version Number: PowerShell 5.1
Dashboard Framework (if applicable): 1.5.14
Operating System: Server 2019

**Additional context**

**Logs**

**Comment by adamdriscoll** [comment] 2021-03-29 14:00
Can you please try using the -ShowPagination parameter of New-UDTable?

**Comment by adamdriscoll** [comment] 2021-04-02 12:48
Closing as I cannot reproduce once I use the -ShowPagination parameter.

**Closed as completed by adamdriscoll** 2021-04-02 12:48 UTC
Labels: bug, PowerShell Universal
