### ISSUE TITLE
PowerShell Universal - Query String Variables Not Populated, [System.Web.HttpContext] Missing Across Multiple PSU Versions and Environments

### ISSUE THREAD

**Issue by RubenT91** [ironmansoftware/powershell-universal#3822] opened 2024-09-23 17:54 UTC
### Version

5.0.7

### Severity

High

### Environment

msi

### Steps to Reproduce

- Install PSU using either the MSI installer or running under IIS.
- Deploy a basic app that uses $query or [System.Web.HttpContext]::Current.Request.QueryString to capture query parameters from the URL.
- Test with the following URL (for example): https://<hostname>/smallApp?smallvalue=hello.
- In PSU 4.4.0 or 5.0.7, attempt to retrieve the query string value via $query or [System.Web.HttpContext]::Current.Request.QueryString.

New-UDApp -Title "Small App" -Content {
    $queryString = [System.Web.HttpContext]::Current.Request.QueryString
    New-UDCard -Title 'Query String Contents' -Content {
        $queryString['smallvalue']
    }
}

- The $query variable is empty or only contains a hash with {“query”, “true”}.
- [System.Web.HttpContext]::Current.Request.QueryString is not accessible (missing [System.Web.HttpContext] class).
- The issue persists across multiple versions of PSU (4.4.0, 5.0.7) and different environments (IIS, MSI installer).

### Expected behavior

```console
The $query variable should contain query string values from the URL.

[System.Web.HttpContext]::Current.Request.QueryString should be accessible to retrieve query parameters.
```

### Actual behavior

```console
The $query variable is empty, containing only {“query”, “true”}.

[System.Web.HttpContext]::Current.Request.QueryString is missing or not accessible in the environment.

The issue persists across different installations and PSU versions, making query string handling unavailable.
```

### Additional Environment data

- .NET Core SDK and Runtime versions installed as per PSU 5.0.7 requirements.
- .NET 8.0.8 Runtime used.
- OS: Windows Server (for IIS), and tested on a fresh Windows 10 machine using the MSI installer.
- PSU 4.2.1 (previously working with the same configuration on IIS, but when the IIS site is restored to 4.4.0 or later versions, the issue occurs).
- Issue occurs both in IIS and non-IIS environments (tested with MSI install on a new machine).

**Comment by adamdriscoll** [comment] 2024-09-23 18:26
This class is not valid in PowerShell Universal: `[System.Web.HttpContext]::Current.Request.QueryString`. We don't pass it to the apps.

I can't reproduce this at the moment. Here is my test app. 

```
New-UDApp -Content { 
    new-UDdynamic -Content {
        $Query["smallValue"]
    } 
}
```

![image](https://github.com/user-attachments/assets/63ac4998-b46c-4602-b324-e32d35a226a1)

**Comment by adamdriscoll** [comment] 2024-09-27 12:44
@RubenT91 - Closing as I cannot reproduce. May need more information if they have a sample app.

**Closed as not planned by adamdriscoll** 2024-09-27 12:44 UTC
Labels: bug, PowerShell Universal, requires triage
