### ISSUE TITLE
new-udtypography , max signs/with

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#2333] opened 2023-04-20 07:26 UTC
### Summary of the new feature / enhancement

It would be perfect if it was possible to create max signs / width for the new-udtypography

**Comment by adamdriscoll** [comment] 2023-04-20 21:39
Duplicate of #2332 - He beat you by a couple hours ;)

**Closed as completed by adamdriscoll** 2023-04-20 21:39 UTC
Labels: enhancement, PowerShell Universal
