### ISSUE TITLE
5.1.2 - Re-Open #1872: UDIcon:  Effects do not work

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#4171] opened 2024-12-21 09:16 UTC
### Description of Issue

UDIcon Effects stopped working again... 
- Beat
- BeatFade
- Bounce
- Fade
- Shake
- Spin

To reproduce:
```
New-UDIcon -Icon 'ThumbsUp' -Shake # does nothing
New-UDIcon -Icon 'ThumbsUp' -Beat # does nothing
```

etc...

Thanks a lot,
Don

### Version

5.1.2

### Severity

Visual

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQLite

### Licensed

Yes

**Comment by adamdriscoll** [comment] 2024-12-22 20:14
I can't reproduce this. I just tried this. Both effects work. 

```
New-UDApp -Content { 
    New-UDIcon -Icon 'ThumbsUp' -Shake # does nothing
    New-UDIcon -Icon 'ThumbsUp' -Beat # does nothing
 }
```

**Comment by donlent** [comment] 2024-12-24 08:44
Hey @adamdriscoll 

Sorry but it does not work for me. I just created a completely new App like you did, just to be sure that it does not have any conflicts related to a theme or whatsoever... The effects just do not work. I've seen it also on acustomer environment still running on 5.0.x.
What environment are you using?

I have Windows Server 2022, Kestrel and as DB SQLite... So nothing special.

Thanks,
Don

**Comment by adamdriscoll** [comment] 2024-12-24 15:24
Interesting. I just tried this on 5.1 and it's not working for me either. It is working in 5.2. It's unclear to me what changed but seems to be resolved in the latest.

**Closed as completed by adamdriscoll** 2024-12-24 15:24 UTC
Labels: bug, PowerShell Universal, P4 - low, Area-Apps, Size - S, v5
