### ISSUE TITLE
5.0.7 - Inline script editor replaces characters when using tab completion

### ISSUE THREAD

**Issue by bt-ndollimount** [ironmansoftware/powershell-universal#3797] opened 2024-09-18 14:13 UTC
### Version

5.0.6

### Severity

Medium

### Environment

msi

### Steps to Reproduce

When editing a script using the inline script editor, you will get suggestions for parameters for a cmdlet when you press - key. If you already have some parameters set in your command and you do this tab completion further back into your existing command, it appears to replace the amount of characters in front of the cursor that the tabbed parameter has.

### Expected behavior

```console
Performing tab completion should insert instead of replace the characters at the cursor.
```

### Actual behavior

```console
Tab completion replaces existing characters at the cursor.
```

### Screenshots/Animations

https://github.com/user-attachments/assets/c53a7cf4-f3f5-4f3a-ac51-32ac6f54604c

**Comment by adamdriscoll** [comment] 2024-09-18 14:23
Duplicate of #3758. I'll move this into our next milestone because this is super annoying.

**Closed as not planned by adamdriscoll** 2024-09-18 14:23 UTC
Labels: bug, PowerShell Universal, requires triage
