### ISSUE TITLE
Add -ShowLoading to New-UDButtonGroupItem

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#3275] opened 2024-04-16 20:02 UTC
### Summary of the new feature / enhancement

as a user, I want the same UI experience with a UDButtonGroupItem that I have with a UDButton (with the addition of it being grouped).  Specifically, I would like it to have the -ShowLoading option that UDButton has.

**Comment by adamdriscoll** [comment] 2024-04-16 20:06
Duplicate of #3247

**Closed as completed by adamdriscoll** 2024-04-16 20:06 UTC
Labels: enhancement, PowerShell Universal
