### ISSUE TITLE
Error in logs, agent not found

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3482] opened 2024-07-22 15:10 UTC
### Version

5.0.0-rc2

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

when i look in the logs there is an error

### Expected behavior

```console
no error
```

### Actual behavior

```console
2024-07-22 09:12:35.949 -05:00 [ERR] Error discovering modules
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'E:\src\psu\Beta\Agents\5.1\Universal.Agent' with working directory 'E:\src\psu\Beta_data\UniversalAutomation\Repository'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at UniversalAutomation.JobProcessManager.StartProcessAsCurrentUser(String powerShellPath, String commandLine, Variable credential, Action`1 onAgentOutput, Dictionary`2 environmentVariables) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\JobProcessManager.cs:line 468
   at UniversalAutomation.JobProcessManager.StartModuleDiscovery(ExecutionEnvironment environment) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\JobProcessManager.cs:line 344
   at Universal.Server.Services.ModuleService.Discover(ExecutionEnvironment environment, Boolean wait) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\ModuleService.cs:line 324
```

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/e9666280-9c28-4142-9766-53179f7c8d50)

**Comment by adamdriscoll** [comment] 2024-07-22 15:32
Duplicate of #3478?

**Comment by Omzig** [comment] 2024-07-22 16:50
> Duplicate of #3478?

oops, ya, ground hogs day for real

**Closed as completed** 2024-07-22 17:11 UTC
Labels: bug, PowerShell Universal, P4 - low
