### ISSUE TITLE
TypeError: S.filter is not a function when viewing source of script

### ISSUE THREAD

**Issue by kp-bit** [ironmansoftware/powershell-universal#2418] opened 2023-05-23 07:07 UTC
### Version

4.0.0-beta4

### Severity

Critical

### Steps to Reproduce

After creating a new script in GUI and trying to open code editor the error TypeError: S.filter is not a function is shown. Edit Properties open fine.

![image](https://github.com/ironmansoftware/issues/assets/61055573/0c92763d-60ac-45c3-b3b8-70a88c07ef3f)

### Expected behavior

```console
Code editor opened
```

### Actual behavior

```console
Error page shown
```

### Additional Environment data

PSU 4.0.0-beta4 nightly build of 22-May-2023 on Windows Server 2019

Related to bug: https://github.com/ironmansoftware/issues/issues/2400

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/61055573/d6b0eefc-d886-448d-bd0e-16ed2f7f1620)

**Comment by kp-bit** [comment] 2023-05-23 12:45
Occasionally the error is a little different:
![image](https://github.com/ironmansoftware/issues/assets/61055573/4248bb20-96b5-41f6-b56b-65500b80761a)

**Comment by kp-bit** [comment] 2023-06-07 06:43
@adamdriscoll, still present in 4.0.0-beta5

**Comment by kp-bit** [comment] 2023-06-13 13:45
And still present in 4.0.0 Release

**Comment by adamdriscoll** [comment] 2023-06-13 19:36
@kp-bit - I can't reproduce this. 

Can you try clearing your browser cache? In Chrome\Edge, I would recommend navigating to the PSU site, pressing F12, clicking the Application tab, click Storage and then click Clear Site Data. 

<img width="207" alt="image" src="https://github.com/ironmansoftware/issues/assets/1256531/9e0971ff-d438-4dd8-8dc6-0b1a124e0ec6">

I've found that Shift+F5 doesn't always completely clear it.

**Comment by kp-bit** [comment] 2023-06-14 06:41
@adamdriscoll, thanks - that partially fixed it, now only scripts in subfolders are affected. The sad part is; that's most of them, but I can move them around, if that's what it takes...

![image](https://github.com/ironmansoftware/issues/assets/61055573/efa1cdfb-05a9-4552-9999-aa939b14d02b)

**Comment by adamdriscoll** [comment] 2023-06-14 09:04
I can reproduce that. This will be resolved in 4.0.1.

**Closed as completed by adamdriscoll** 2023-06-14 09:04 UTC
Labels: bug, PowerShell Universal, completed, P1 - critical
