### ISSUE TITLE
Upgrade from 5.0.16 to 5.10  An error occured. Cannot access a disposed object.

### ISSUE THREAD

**Issue by cmtrios** [ironmansoftware/powershell-universal#4139] opened 2024-12-12 16:42 UTC
### Description of Issue

Recently upgrade via the MSI installed from 5.0.16 to 5.1
This message appears now when i try to edit my existing application. It also appears when i edit my endpoints.

Object name: 'Microsoft.JSInterop.DotNetObjectReference`1[[BlazorMonaco.Editor.Editor, BlazorMonaco, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null]]'. at Microsoft.JSInterop.DotNetObjectReference`1.get_Value() at BlazorMonaco.Editor.Global.Create(IJSRuntime jsRuntime, String domElementId, StandaloneEditorConstructionOptions options, EditorOverrideServices overrideServices, DotNetObjectReference`1 dotnetObjectRef) at BlazorMonaco.Editor.StandaloneCodeEditor.OnAfterRenderAsync(Boolean firstRender) at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

### Version

5.10

### Severity

Low

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQL

### Licensed

No

### Additional Environment data

Win11 23H2, PowerShell 7.46, Linux MS SQL Server 2022. Edge Browser.

**Comment by adamdriscoll** [comment] 2024-12-12 16:44
This is a duplicate of: https://github.com/ironmansoftware/powershell-universal/issues/4131

**Closed as not planned by adamdriscoll** 2024-12-12 16:44 UTC
Labels: bug, PowerShell Universal, requires triage, v5
