### ISSUE TITLE
PS 5.1 Dashboards start with an invalid PSModulePath, which causes module version conflicts and .NET induced crashes.

### ISSUE THREAD

**Issue by JCrabtree911** [ironmansoftware/powershell-universal#3801] opened 2024-09-18 17:48 UTC
### Version

5.0.6

### Severity

Critical

### Environment

msi

### Steps to Reproduce

5.07 did not resolve this UD5.X bug.  PS5.1 Dashboards don't startup. They fail with the error message below, which points to a .NET related error due to the PSModulePath being wrong. This causes Win PS5.1 to try to load .NET CORE modules when it should be loading regular .NET

```
One or more errors occurred

The following error occurred while loading the extended type data file: Error in TypeData
"System.Security.AccessControl.ObjectSecurity": The member AuditToString is already present. Error in TypeData
"System.Security.AccessControl.ObjectSecurity": The member AccessToString is already present. Error in TypeData
"System.Security.AccessControl.ObjectSecurity": The member Sddl is already present. Error in TypeData
"System.Security.AccessControl.ObjectSecurity": The member Access is already present. Error in TypeData
"System.Security.AccessControl.ObjectSecurity": The member Group is already present. Error in TypeData
"System.Security.AccessControl.ObjectSecurity": The member Owner is already present. Error in TypeData
"System.Security.AccessControl.ObjectSecurity": The member Path is already present.

```

### Expected behavior

```console
PS 5.1 Dashboards should start and run
```

### Actual behavior

```console
They crash with the TypeData error above.
```

### Additional Environment data

Windows Server 2019 Datacenter, 1809
PowerShell Universal Dashboard 5.07

**Comment by adamdriscoll** [comment] 2024-09-18 19:29
I've been able to reproduce this and believe we have a fix. Additional testing is needed but it seems to be working fine on 2019-1909 and I will also try on1809. This will be included in tonight's nightly build if you want to verify in your environment.

**Comment by JCrabtree911** [comment] 2024-09-18 20:28
I won't be able to verify on 2024-09-19, but I can grab a copy and test on 2024-09-20 and report back.

**Comment by adamdriscoll** [comment] 2024-09-19 13:15
I verified the nightly on both 1909 and 1809 and apps are working for me. If that's not the case for you, I will reopen and we can further investigate.

**Closed as completed by adamdriscoll** 2024-09-19 13:15 UTC
Labels: bug, PowerShell Universal, P1 - critical, Area-Apps, Size - M

**Comment by JCrabtree911** [comment] 2024-09-23 22:08
With the UD 5.10 nightly build my PS 5.1 dashboards load, but my UDDataGrids are empty. They have column names and I can confirm, using write-host and the UD logs, that the data is properly retrieved and passed into the call to New-UDDataGrid, and the identical code works correctly in UD 4.3.4
