### ISSUE TITLE
String Parameters functioning differently from version 4 to 5

### ISSUE THREAD

**Issue by NLABC** [ironmansoftware/powershell-universal#4084] opened 2024-11-20 19:39 UTC
### Description of Issue

String Parameters don't allow multiple selections in version 5.
Code block below "
param(
[Parameter(Mandatory)]
[ValidateSet("Option1", "Option2", "Option3")]
[string[]]$ParameterName
)
"
In version 4, you can select Option1, Option2, and/or Option 3.
In version 5, once you select an option, the pulldown closes.  

### Version

5.0.16

### Severity

Medium

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQL

### Licensed

Yes

### Additional Environment data

Microsoft Windows Server 2022 Datacenter
Powershell version 5.1

### Screenshots/Animations

![PSU4TestParam](https://github.com/user-attachments/assets/92f50723-f537-438c-bb0f-42b18e01fbb9)
![PSU5TestParam](https://github.com/user-attachments/assets/61381c68-8831-40eb-9944-3a54cbe84b1c)

**Comment by NLABC** [comment] 2024-11-20 19:41
Screenshots is how it looks in version 4 (which allows multiple selections) vs version 5 (which only allows 1 selection).

**Comment by NLABC** [comment] 2024-11-22 15:19
I tried nightly build 5.1.0 (11964051188), and this issue still exist.  Can only select 1 from the dropdown, instead of multiple.

**Comment by RubenT91** [comment] 2024-12-06 15:19
**Summary of the Issue:**
After upgrading to PSU 5.1.0 (12021295097), subsequent nightly builds from November 27, 2024, onward fail to start the PSU service. The issue appears related to database migrations and application restarts.

**Relevant Event Log Details:**
**RestartManager Errors:**

Event 10010, RestartManager

Application Universal.Agent.exe cannot be restarted due to SID mismatch.
Path: C:\Program Files (x86)\Universal\Universal.Agent.exe
Application Universal.Agent.exe under C:\Program Files (x86)\Universal\Agents\5.1\win-x64 also reports the same SID mismatch.

Event 10007, RestartManager

Application or service PowerShell Universal could not be restarted.

**Application Error Logs (Event 1000):**

Faulting application: Universal.Server.exe
Faulting module: KERNELBASE.dll
Exception Code: 0xe0434352
Description: Application terminated due to an unhandled exception.

**.NET Runtime Error (Event 1026):**

Application: Universal.Server.exe
Exception: Microsoft.Data.SqlClient.SqlException
Details: 'FK_Roles_Roles_RoleId' is not a constraint.
Could not drop constraint during database migration.
Stack trace points to PowerShellUniversal.SQL.DatabaseFeature.InitializeDatabase and Microsoft.EntityFrameworkCore.Migrations.

**Steps to Reproduce:**
Upgrade from PSU 5.1.0 (12021295097) to any nightly build released after November 27, 2024.
Observe the service failing to start, with the above errors logged in the Event Viewer.
Rollback to PSU 5.1.0 (12021295097), which resolves the issue.

**Notes:**
The nightly builds fail during the database migration process due to a missing or improperly handled constraint (FK_Roles_Roles_RoleId).
Service restart attempts by RestartManager also fail due to SID mismatches.

**Request:**
Please review this information and provide guidance on resolving the issue in future nightly builds. If a patch is already planned, let us know so we can plan accordingly.

**Comment by adamdriscoll** [comment] 2024-12-06 15:38
@RubenT91 - Upgrading between nightly builds is not supported. There can be schema changes, like the one in this error, that cause the database to be in an invalid state. The database needs to be rolled back to version 5.0.16 in order for the new 5.1 nightly build to update the schema properly.

**Closed as completed** 2024-12-06 15:49 UTC
Labels: bug, PowerShell Universal, Area-AdminConsole, Area-Automation, P3 - medium, Size - S, v5
