### ISSUE TITLE
gitsync settings are not saved

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1824] opened 2022-12-15 06:37 UTC
### Steps to Reproduce

As default it seem to be set for "Use database" but when I'm trying to change that as I want to use it in the old fashion way the settings are not saved.
Next time I open Git settings it's back to "Use database"

### Expected behavior

```console
Save git settings
```

### Actual behavior

```console
are not saving git settings and gets reverted back to "Use database"
```

### Environment data

PSU 3.6.1
SQL 2019
Win 2022
PS 7.3.1

**Comment by adamdriscoll** [comment] 2022-12-16 14:25
Duplicate of: https://github.com/ironmansoftware/issues/issues/1827

**Closed as completed by adamdriscoll** 2022-12-16 14:25 UTC
Labels: bug, PowerShell Universal
